namespace ScenarioRunner.ScenarioFormat
{
	public enum ScenarioCommandType
	{
		LAUNCH_GUI,
		OPEN_GUI,
		CLOSE_GUI,
		CLOSE_DIALOG,
		OPEN_CALC_DETAIL,
		CLOSE_CALC_DETAIL,

		SELECT_SHIKIGAMI,
		EQUIP_MITAMA,
		LOAD_MITAMA,
		COMPARE_SNAPSHOT,

		SAVE_MITAMA,
		SAVE_BUILD,
		SAVE_SNAPSHOT,
		LOAD_SAVED_MITAMA,
		LOAD_SAVED_BUILD,
		COMPARE_SAVED_SNAPSHOT,

		CALCULATE,
		CLEAR,
		CLEAR_SHIKIGAMI,

		RELOAD_SHIKIGAMI,
		BREAK_SHIKIGAMI_HEADER,
		REMOVE_SHIKIGAMI,
		CREATE_SHIKIGAMI_BACKUP,
		RECOVER_SHIKIGAMI,

		CHECK_CALCULATION,
		CHECK_CALC_DETAIL,
		CHECK_CLEARED,
		CHECK_SHIKIGAMI,
		CHECK_DIALOG,
		CHECK_SNAPSHOT_COMPARISON,

		WAIT_SHIKIGAMI_AUTO_REPAIR
	}
}
